### ISSUE TITLE
Demo site emojisearch.app functioning

### ISSUE THREAD

**Issue by taesungh** [lilianweng/emoji-semantic-search#3]
Hello Lilian,

I wanted to try out your Emoji Search app, but it seems that the demo is not functioning.
The `fetchSearchResults` function makes a POST request to `/search` on the server running on Heroku, but the server responds with status 503 and shows Heroku's application error page.

I am suspecting this is because Heroku began [shutting down free dynos on November 28](https://blog.heroku.com/next-chapter), but the issue could just as well be something wrong with the app.

I hope you still have the capacity to maintain this application.

**Comment by lilianweng** [comment]
@taesungh Thanks for reporting the issue! I spent some time today to get it fixed and it should work right now and should be faster than before too. Enjoy!
