### ISSUE TITLE
emoji Embeddings Inquiry 🤖

### ISSUE THREAD

**Issue by h393727323** [lilianweng/emoji-semantic-search#5]
Hi Lilian 😊, I love this project so much!!!! ❤️ I'm also a huge emoji enthusiast 🤩! I've tried generating embeddings using emojis or emoji messages, but they turn out different from what you have in emoji-embeddings.jsonl. 🤔 Would it be possible for you to share some details about the embeddings in emoji-embeddings.jsonl? 🙏

**Comment by chrisqi2023** [comment]
I'm so sorry for the inconvenience. I found the answer in build.py. Thank you again for creating it! 😊🙏

**Comment by h393727323** [comment]
I found the answer in build.py , thanks once again for your creation! 🙏✨
